### ISSUE TITLE
O botão de próximo capítulo ao final do capítulo 7 leva a um erro 404

### ISSUE THREAD

**Issue by vitorfrois** [agomesp/metodoFacil#13]
![image](https://user-images.githubusercontent.com/46361092/154785009-d3ebea50-ee62-4879-9d71-83e6e93a42a3.png)
O usuário cai na página https://metodofacil.org/chapters/07-economizando-tempo.html quando deveria cair em https://metodofacil.org/chapters/08-economizando-tempo.html

**Comment by agomesp** [comment]
solved #29
